version: '3'

services: 

  laravel:
    build: 
      context: ./laravel
      dockerfile: Dockerfile.prod
    image: marcus21/laravel:prod
    container_name: laravel
    networks:
      - laranet

  nginx:
    build: 
      context: ./laravel
      dockerfile: Dockerfile.prod
    image: marcus21/nginx:prod 
    container_name: nginx
    networks:
      - laranet
    ports:
      - "8080:80"

networks:
  laranet:
    driver: bridge